### ISSUE TITLE
Face ID crashes on iPhone X iOS 11.3

### ISSUE THREAD

**Issue by rickymarks** [smstuebe/xamarin-fingerprint#100]
The following method is crashing on iOS 11.3, iPhone X:
await CrossFingerprint.Current.AuthenticateAsync(string);

The weird thing is no stack trace is being displayed. Visual Studio just stops debugging. 

I tried it in a physical device and on a simulator.

I Also tried it in a iPhone X, iOS 11.2 and it works perfect.

## Steps to reproduce

1. Call the await CrossFingerprint.Current.AuthenticateAsync(string);

## Expected behavior
Should open the face id authentication dialog

## Actual behavior
App Crashes

### Crashlog

No stack trace is being displayed on Visual Studio. The IDE just stops debugging. 

## Configuration

**Version of the Plugin:** 1.4.6

**Platform:** iOS 11.3

**Device:** iPhone X

**Comment by smsissuechecker** [comment]
Hi @rickymarks,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
Hmm a crashlog would be nice, because I don't own a iPhone X. On the simulator it doesn't crash, right?!
Does the demo App crash too, if you build everything on your own?

**Comment by rickymarks** [comment]
It also crashes on the simulator. I've attached the crash log of the iPhone X simulator.

I have not tried it in the demo app.

[FM_Mobile_App.iOS_2018-04-16-141122_Ricardos-Mac-mini.txt](https://github.com/smstuebe/xamarin-fingerprint/files/1916618/FM_Mobile_App.iOS_2018-04-16-141122_Ricardos-Mac-mini.txt)

**Comment by tjismh** [comment]
Looks like this is related to the need to have a NSFaceIDUsageDescription in the info.plist file which seems to be enforced with ios 11.3?

**Comment by smstuebe** [comment]
Thx @tjismh for the finding. I'll add it to the documentation.
@rickymarks can you confirm it works on an iPhone X, too?

**Comment by rickymarks** [comment]
As soon as I can test it i'll confirm it.

**Comment by mister-giga** [comment]
@smstuebe I had same issue, wish it was in was mentioned in documentation

**Comment by rickymarks** [comment]
I could finally work back on the project and tested it on a physical iPhone X and i can confirm it works
