### ISSUE TITLE
[Question] What are the system requirements?

### ISSUE THREAD

**Issue by wegascee** [smstuebe/xamarin-fingerprint#109]
I want to know the minimum system requirements for Android. You list Xamarin.Android 4.4. Do you mean Android 4.4 (API Level 19)? I'm asking because only since Android 6 (API level 23) fingeprint authentication is supported directly by the OS. Also you mention

> target SDK version has to be >= 6.0

What happens on an Android 4.4 device with fingeprint sensor (if exists)? Does `IsAvailableAsync()` only returns false?

**Comment by smsissuechecker** [comment]
Hi @wegascee,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
