### ISSUE TITLE
MvvmCross.Platform.Exceptions.MvxException: could not load plugin assembly for type MvvmCross.Plugins.Fingerprint.Android.PluginLoader

### ISSUE THREAD

**Issue by JelleDamen** [smstuebe/xamarin-fingerprint#11]
[mono] Unhandled Exception:
[mono] MvvmCross.Platform.Exceptions.MvxException: could not load plugin assembly for type MvvmCross.Plugins.Fingerprint.Android.PluginLoader
[mono]   at MvvmCross.Platform.Plugins.MvxFilePluginManager.LoadAssembly (System.Type toLoad) [0x00071] in D:\git\MvvmCross\MvvmCross\Platform\Platform\Plugins\MvxFilePluginManager.cs:76 
[mono]   at MvvmCross.Platform.Plugins.MvxFilePluginManager.FindPlugin (System.Type toLoad) [0x00000] in D:\git\MvvmCross\MvvmCross\Platform\Platform\Plugins\MvxFilePluginManager.cs:39 
[mono]   at MvvmCross.Platform.Plugins.MvxPluginManager.LoadPlugin (System.Type toLoad) [0x00000] in D:\git\MvvmCross\MvvmCross\Platform\Platform\Plugins\MvxPluginManager.cs:150 
[mono]   at MvvmCross.Platform.Plugins.MvxPluginManager.ExceptionWrappedLoadPlugin (System.Type toLoad) [0x00000] in D:\git\MvvmCross\MvvmCross\Platform\Platform\Plugins\MvxPluginManager.cs:122 

I've followed the instructions, but I get this error while starting the app. Then it crashes. Any ideas ? I'm using the latest beta

**Comment by smstuebe** [comment]
Might have to do something with assembly versions. I'll have a look, later.

**Comment by smstuebe** [comment]
@JelleDamen What's your MvvMCross version are they the same in core and on android?

**Comment by smstuebe** [comment]
should be fixed in 1.2.0

**Comment by rodhemphill** [comment]
Hi @smstuebe. Do you know what happened to this? I have exactly the same problem and I've been trying to resolve it for a couple of weeks now. I'm on MVVMCross 4.2.3, have the same version in Droid and Core, running Forms with MVVMCross.

**Comment by yyuzyk** [comment]
Hi @rodhemphill and @smstuebe .
Did you fix it?
It works when you select Linking -> Sdk Assemblies Only.
But, when you select Linking -> Sdk and User Assemblies -> crash with that error.
@rodhemphill and @smstuebe advice, please.
