### ISSUE TITLE
AllowAlternativeAuthentication is not working in Android

### ISSUE THREAD

**Issue by karant0007** [smstuebe/xamarin-fingerprint#110]
HI There

i'm using this fingerprint package in my application, but having one issue

when i'm setting up AllowAlternativeAuthentication = true;
that didn't working in android, i mean i'm not getting device pin authentication option while i disable the fingerprint authentication

This feature working fine in IOS but not in android.

can you please help me with this?

Thanks

**Comment by smsissuechecker** [comment]
Hi @karant0007,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by bastianbecker21** [comment]
@karant0007 Did you get a solution for this issue?

**Comment by smstuebe** [comment]
@karant0007 @bastianbecker21 
disucssion goes on here: https://github.com/smstuebe/xamarin-fingerprint/issues/151
