### ISSUE TITLE
There is no "Dialog Title" on Android

### ISSUE THREAD

**Issue by khoduley** [smstuebe/xamarin-fingerprint#113]
https://github.com/smstuebe/xamarin-fingerprint/blob/c5bf6af1431b3eb030d0bf4c89476b67cf553dce/src/Plugin.Fingerprint.Android/Dialog/FingerprintDialogFragment.cs

In FingerprintDialogFragment.cs you create a dialog with DialogFragmentStyle.NoTitle; Please, can you fix this or create a property to set it.

        public override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            RetainInstance = true;
            SetStyle(DialogFragmentStyle.NoTitle, 0);
        }

**Comment by smsissuechecker** [comment]
Hi @khoduley,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
Hi @khoduley,

I'm currently working on getting rid of a custom dialog. With Android Pie, Google introduced a default one. The future version of this plugin will use this dialog instead, because it's recommended by google.

**Comment by khoduley** [comment]
thank you so much for the answer, I will wait)

**Comment by Binaryraja** [comment]
is this completed in latest version? I tried to overwrite the Window style. But it's not working.
