### ISSUE TITLE
compatibility problem with .net standard mvvmcross 6.2.1

### ISSUE THREAD

**Issue by burimameti** [smstuebe/xamarin-fingerprint#115]
there is compatibility problem with mvvmcross 6.2.1 and .net standard 2.0 can you help solve this problem and aupdate it on nuget

**Comment by smsissuechecker** [comment]
Hi @burimameti,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
