### ISSUE TITLE
Expose LocalizedFallbackTitle for TouchID

### ISSUE THREAD

**Issue by arctouch-oberdanbitencourt** [smstuebe/xamarin-fingerprint#12]
Hi, I've come across the need of customizing the text of the LocalizedFallbackTitle for TouchID and noticed there's no way of doing it with the plugin. Once you fail reading a finger for the first time the option "Enter Password" is shown, but I can't customize the text or even hide it in an easy way.

This is controlled by [LAContext.LocalizedFallbackTitle](https://developer.xamarin.com/api/property/LocalAuthentication.LAContext.LocalizedFallbackTitle) property.

Luckily, I have no problems using the standard behavior, but I wonder if I want something a bit more custom I'd have to do it directly with Xamarin.iOS apis.

My suggestion would be to expose this property on the `IFingerprint` interface and reusing it on both platforms.

**Comment by smstuebe** [comment]
Good idea. I didn't know about this feature.

**Comment by smstuebe** [comment]
included in 1.3.0-beta2. Feedback?
