### ISSUE TITLE
how to change in progress green ball when authenticating

### ISSUE THREAD

**Issue by TedMobile** [smstuebe/xamarin-fingerprint#121]
Hi
new to this plugin.Its not an issue!!
When placing the finger on the sensor the plugin shows a green ball when in progress. How can I change this green ball to be a finger or something else?

thanks

**Comment by smsissuechecker** [comment]
Hi @TedMobile,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
