### ISSUE TITLE
Android crash : Error inflating class adaptive-icon

### ISSUE THREAD

**Issue by RSadocchi** [smstuebe/xamarin-fingerprint#124]
(sorry form my english...)
I've a cross platform app with Xamarin.Forms (3.6.0.220655), Xamarin.Android... (28.0.0.1) and Plugin.Fingerprint (1.4.9), with PCL.

When I try biometric auth in Android this error is throw:
Android.Views.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class adaptive-icon

I've try different emulator: 
--- Oreo 8.0 API 26 Google Play x86 => 
--- Oreo 8.1 API 27 Google APIs x86 =>
ACTION: Plugin.Fingerprint.CrossFingerprint.Current.AuthenticateAsync("touch", default)
EXCEPTION: Android.Views.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class adaptive-icon

--- Nugat 7.1 API 25 Google Play x86 => 
ACTION: Plugin.Fingerpring.CrossFingerprint.Current.IsAvailableAsync(false)
EXCEPTION: Android.Views.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class adaptive-icon

If I dont use fingerprint, but a simple login with username and password it works.

In iOS it works, I've try in iPhone 6s emulator with iOS 12.1

Someone can help me? 
Thanks

**Comment by smsissuechecker** [comment]
Hi @RSadocchi,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by RSadocchi** [comment]
EDIT;

If in MainActivity I'm use 
CrossFingerprint.SetCurrentActivityResolver(() => CrossCurrentActivity.Current.Activity);
before CrossFingerprint.SetCurrentActivityResolver(() => this);

is throw this exception:
System.NullReferenceException: Object reference not set to an instance of an object
