### ISSUE TITLE
How to center the cancel button on DialogFragment?

### ISSUE THREAD

**Issue by aimore** [smstuebe/xamarin-fingerprint#125]
![fingerprint](https://user-images.githubusercontent.com/8807639/54325387-023a0780-4656-11e9-944d-9c2dcf3aa344.png)

**Comment by smsissuechecker** [comment]
Hi @aimore,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
