### ISSUE TITLE
Android crash : Error inflating class adaptive-icon

### ISSUE THREAD

**Issue by RSadocchi** [smstuebe/xamarin-fingerprint#126]
(sorry form my english...)
I've a cross platform app with Xamarin.Forms (3.6.0.220655), Xamarin.Android... (28.0.0.1) and Plugin.Fingerprint (1.4.9), with PCL on VS2019preview and VS2017 for Windows.

In iOS it works, I've try in iPhone 6s emulator with iOS 12.1.
If I dont use fingerprint, but a simple login with username and password it works.

## Steps to reproduce

1. In Android MainActivity.cs
protected override void OnCreate(Bundle savedInstanceState)
{
   TabLayoutResource = Resource.Layout.Tabbar;
   ToolbarResource = Resource.Layout.Toolbar;
   base.OnCreate(savedInstanceState);
   global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
   CrossCurrentActivity.Current.Activity = this;
   CrossFingerprint.SetCurrentActivityResolver(() => CrossCurrentActivity.Current.Activity);
   LoadApplication(new App());
}

2. In PCL MainPage, before invoke the authentication I'm check await CrossFingerprint.Current.IsAvailableAsync(false); (works)

3. In PCL MainPage
--NOW
var dialogConfig = new AuthenticationRequestConfiguration("test")
{
    AllowAlternativeAuthentication = false,
    UseDialog = true,
    CancelTitle = "Cancel",
};
if ((await CrossFingerprint.Current.AuthenticateAsync(dialogConfig)).Authenticated)
    await DisplayAlert("Auth", "ok", "OK");
else
    await DisplayAlert("Auth", "error", "OK");
--BEFORE
var authRes = await CrossFingerprint.Current.AuthenticateAsync("test");
//...

## Expected behavior
Open the dialog waiting the fingerprint touch

## Actual behavior
Emulator:
Oreo 8.0 API 26 Google Play x86 
Oreo 8.1 API 27 Google APIs x86  
Nugat 7.1 API 25 Google Play x86 
    => EXCEPTION: 
Android.Views.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class adaptive-icon

## Configuration
Oreo 8.0 API 26 Google Play x86 
Oreo 8.1 API 27 Google APIs x86  
Nugat 7.1 API 25 Google Play x86 

**Version of the Plugin:** e.g. 1.4.9

**Platform:** e.g. Android 7.1/8.0/8.1

**Device:** e.g. Emulator

**Comment by smsissuechecker** [comment]
Hi @RSadocchi,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.
