### ISSUE TITLE
Is this plugin still supported or live?

### ISSUE THREAD

**Issue by developer9969** [smstuebe/xamarin-fingerprint#127]
Hi
Extremely grateful for the plugin!!
I totally understand that it's free and time is always a problem, we all have very busy life.

but it would be helpful to know if this plugin is supported or still active.

There seems to be quite few issues with resume but hardly any replies

many thanks

**Comment by smsissuechecker** [comment]
Hi @developer9969,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by tranb3r** [comment]
It would be great to know if this plugin is still maintained.
The only alternative that makes sense would be an integration in xamarin.essentials (see xamarin/Essentials#71)

**Comment by Jacko1394** [comment]
Im curious as to the status of this library also.
Hope it's getting maintained 👍

**Comment by smstuebe** [comment]
@developer9969 @Jacko1394 
disucssion goes on here: https://github.com/smstuebe/xamarin-fingerprint/issues/151
