### ISSUE TITLE
Get "NoFingerprint" from GetAvailabilityAsync

### ISSUE THREAD

**Issue by tschennie** [smstuebe/xamarin-fingerprint#128]
## Actual behavior
What should I do, when I get "NoFingerprint" from function GetAvailabilityAsync()? What does it mean, fingerprint is not set? With my smartphone I already use the fingerprint, so it's set on my smartphone. Do I have to set something more within the app? I just have following in the MainActivity:

```
CrossCurrentActivity.Current.Activity = this;
CrossFingerprint.SetCurrentActivityResolver(() => CrossCurrentActivity.Current.Activity);
```

## Configuration

**Version of the Plugin:** current stable version

**Platform:** Android min SDK 21, Target SDK 27

**Device:** HUAWEI P20 Lite

**Comment by smsissuechecker** [comment]
Hi @tschennie,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by tschennie** [comment]
Ok, I don't know why, but something deleted my fingerprint settings on my smartphone. I recognized that the fingerprint is also not working anymore for other apps..
