### ISSUE TITLE
NoSensor error Galaxy S8

### ISSUE THREAD

**Issue by yero007** [smstuebe/xamarin-fingerprint#129]
1. Calling the authenticate async method

## Expected behavior
Show the fingerprint dialog

## Actual behavior
I get a no sensor error result

### Crashlog
No exception. The app does not crash just the result is wrong. 

## Configuration

**Version of the Plugin:** latest

**Platform:** Android 9.0

**Device:** Samsung Galaxy S8

The code worked on Android 8.0 until I updated the software to 9.0. Has anyone else had this issue?

**Comment by smsissuechecker** [comment]
Hi @yero007,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by marcelam28** [comment]
I’m having the same issue...

**Comment by Davidoff94** [comment]
I also had this issue. Can anyone help us?

**Comment by petricelealexandru** [comment]
I am experiencing the same issue.

**Comment by IustinT** [comment]
Tested on Samsung S8, Android 9 on plugin v1.4.8 and v1.4.9 and it worked fine.

v1.4.7 did not work, it logs some errors to the console without crashing the app.

**Comment by yero007** [comment]
Thank you! The issue was with a miss management between the core and the android version. It worked on 1.4.9!
