### ISSUE TITLE
Allow regular login via password on Android

### ISSUE THREAD

**Issue by arctouch-oberdanbitencourt** [smstuebe/xamarin-fingerprint#13]
Currently for the default [FingerprintDialog fragment](https://github.com/smstuebe/xamarin-fingerprint/blob/master/src/Plugin.Fingerprint.Android/Resources/layout/FingerprintDialog.axml) button `second_dialog_button` is commented out.

On iOS we have the ability to drive the user to a regular login page by using a fallback. The idea would be to have the same for Android.

What about exposing `FallbackAction` to `IFingerprint` where I can register to?

**Comment by smstuebe** [comment]
included in 1.3.0-beta2. Feedback?

**Comment by KyleKofoed** [comment]
Hey @smstuebe!

Was this moved to master? Also, does it follow similar implementation to the goToBackup method provided in the example [here](https://github.com/googlesamples/android-FingerprintDialog/blob/master/Application/src/main/java/com/example/android/fingerprintdialog/FingerprintAuthenticationDialogFragment.java)?

Thank you for your time,
Kyle

**Comment by smstuebe** [comment]
not yet, I'm currently fighting with a stupid build bug #84. :<

**Comment by KyleKofoed** [comment]
Oh, is that related or just taking priority? I may be able to help out if the former is the case.
