### ISSUE TITLE
Detect Changed Fingerprint

### ISSUE THREAD

**Issue by marcuskammerlander** [smstuebe/xamarin-fingerprint#131]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Integrate Plugin in App

2. Activate and use Plugin to Authenticate

3. Change Fingerprint in System

## Expected behavior
Plugin should throw exception "Biometric Data has changed"

## Actual behavior
you can still use Fingerprint

**Comment by smsissuechecker** [comment]
Hi @marcuskammerlander,

I'm the friendly issue checker.
It seems like (62.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by Phenek** [comment]
Hey @marcuskammerlander 
I don't understand your expected exception.
The function AuthenticateAsync have to be called one time at the login for example.
The result is kind of immediate, the Fingerprint has no time to be changed at this time.

So maybe your are searching for an event that will fire when a new fingerprint is added or removed? 
Did you check if it's possible to implement this kind of event on iOS and Android too?
Let me know.
Regards,

**Comment by GuidoNeele** [comment]
I think what he means is that if you add or remove a fingerprint in the system settings then you should be able to detect if this has happend or not. That way you can force the user to reactivate biometrics for your app.

https://stackoverflow.com/questions/44515668/android-fingerprint-detect-new-finger-added
https://stackoverflow.com/questions/38397477/touchid-detect-new-fingerprints-added-when-does-evaluatedpolicydomainstate-c

**Comment by marcuskammerlander** [comment]
@Phenek @GuidoNeele is right. That is exactly what i mentioned

**Comment by mshuf** [comment]
+1

@marcuskammerlander This feature request has been inactive for some time. Did you achieve a work-around?
