### ISSUE TITLE
[Android] UseFingerprint is deprecated, please use UseBiometric instead

### ISSUE THREAD

**Issue by Raystorm7** [smstuebe/xamarin-fingerprint#134]
Hi,
since the permission **Android.Manifest.Permission.UseFingerprint** is deprecated, I have tried to use **Android.Manifest.Permission.UseBiometric** but when I check for fingerprint support, the method **CrossFingerprint.Current.AuthenticateAsync** it returns false.

I need to include the deprecated permission to make it works.

It is possible to add support for **Android.Manifest.Permission.UseBiometric**?

Thank you.

## Expected behavior
**CrossFingerprint.Current.AuthenticateAsync** returns true without **UseFingerprint** but with **UseBiometric**

## Actual behavior
**CrossFingerprint.Current.AuthenticateAsync** returns false

## Configuration

**Version of the Plugin:** 1.4.9

**Platform:** Android MediaPad M5 10' (Android version 9)

**Comment by smsissuechecker** [comment]
Hi @Raystorm7,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by leonvandebroek** [comment]
i am currently experiencing the same problem. Can't use fingerprint on Android 9 either.
