### ISSUE TITLE
".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework 

### ISSUE THREAD

**Issue by livetouchbr** [smstuebe/xamarin-fingerprint#135]
Hi, I'm using Visual Studio Community for Mac 8.1 and my project has target .NET Portable - PCL 4.5 - Profile259.

And when I compile the project I have this error. Can you help? What version the plugin was built, pcl 4.5 ou 5.0 ?

/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2134,5): warning MSB3274: The primary reference "Plugin.Fingerprint, Version=1.4.9.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".

/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2134,5): warning MSB3274: The primary reference "Plugin.Fingerprint.Abstractions, Version=1.4.9.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".
/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2134,5): warning MSB3275: The primary reference "Plugin.Fingerprint, Version=1.4.9.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Plugin.Fingerprint.Abstractions, Version=1.4.9.0, Culture=neutral, PublicKeyToken=null" which was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".
ViewModels/TelaMeusDadosViewModel.cs(71,41,71,55): warning CS0108: 'TelaMeusDadosViewModel._dadosSettings' hides inherited member 'TDBaseViewModel._dadosSettings'. Use the new keyword if hiding was intended.
Servicos/Biometria.cs(1,14,1,25): error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?)
Servicos/Biometria.cs(2,14,2,25): error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?)
Servicos/Biometria.cs(88,58,88,89): error CS0246: The type or namespace name 'FingerprintAuthenticationResult' could not be found (are you missing a using directive or an assembly reference?)
Servicos/Biometria.cs(132,41,132,72): error CS0246: The type or namespace name 'FingerprintAuthenticationResult' could not be found (are you missing a using directive or an assembly reference?)

**Comment by smsissuechecker** [comment]
Hi @livetouchbr,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by LucGal** [comment]
Same error for me

**Comment by ronpf** [comment]
same error. 
Is there a different PCL profile we need to target? Convert to .NETStandard v?.?
I'm currently set to PCL 4.5 - Profile111

**Comment by smstuebe** [comment]
PCL is dead. You should switch to .net standard. I targeted a very low net standard version, to ensure it is compatible.
259 should be fine, but I can't fix the broken tooling around PCLs and net standard.

**Comment by LucGal** [comment]
Using Mono to 5.20.x fix the problem.

You can download from here:
https://www.mono-project.com/download/stable/
