### ISSUE TITLE
Plugin.Fingerprint is not working 

### ISSUE THREAD

**Issue by pamela032709** [smstuebe/xamarin-fingerprint#139]
I am currently using FingerPrint plugin V 1.4.9 in all of my 3 projects with no issues until I

updated visual studio to

Visual Studio Enterprise 2019 for Mac
Version 8.1.5 (build 9)
Installation UUID: 7692fd6e-5645-498f-b996-0c7a5632bf5c
GTK+ 2.24.23 (Raleigh theme)
Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

Package version: 518010028
Mono Framework MDK
Runtime:
Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
Package version: 518010028

NuGet
Version: 5.0.2.5988

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
2.1.11
2.1.9
2.1.8
2.1.2
2.0.5
2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.700/Sdks
SDK Versions:
2.1.700
2.1.505
2.1.504
2.1.302
2.1.4
2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

Xamarin.Profiler
Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

Xamarin.Android
Version: 9.3.0.23 (Visual Studio Enterprise)
Commit: HEAD/d0b48056f
Android SDK: /Users/compriop/Library/Developer/Xamarin/android-sdk-macosx
Supported Android versions:
5.0 (API level 21)
6.0 (API level 23)
7.0 (API level 24)
7.1 (API level 25)
8.0 (API level 26)
8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information:
Mono: mono/mono@3a07bd4
Java.Interop: xamarin/java.interop@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip@b95cf3f
ProGuard: xamarin/proguard@905836d
SQLite: xamarin/sqlite@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools@acabd26

Microsoft Mobile OpenJDK
Java SDK: /Users/compriop/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

Apple Developer Tools
Xcode 10.2.1 (14490.122)
Build 10E1001

Xamarin.Mac
Version: 5.10.0.157 (Visual Studio Enterprise)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

Xamarin.iOS
Version: 12.10.0.157 (Visual Studio Enterprise)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 801050009
Git revision: bd0ab28ba941b19b39322247db020dcd0fb305d0
Build date: 2019-07-03 17:15:21+00
Build branch: release-8.1
Xamarin extensions: 8cc25b5cb090e6c23b62a7901000c299977eb08d

Operating System
Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
Mon Mar 11 20:40:32 PDT 2019
root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

Project info
Target Framework is .Net Portable 4.5-Profile 111

Steps to reproduce
Create a project using this plugin using visual studio 2019 and latest Xam.ios tools referenced at the begging.
2.delete and add again the plugin and the error keeps happening. I have been using this for over a year and this is the first time I have this issue.

## Expected behavior
No error since the plugin is being referenced
using Plugin. Fingerprint;

## Actual behavior
/Users/Desktop/myapp/VM/LoginViewModel.cs(14,14): Error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?) (CS0234) (myapp)

### Crashlog

/Users/Desktop/myapp/VM/LoginViewModel.cs(14,14): Error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?) (CS0234) (myapp)

## Configuration

**Version of the Plugin:** 1.4.9

**Platform:** e.g. iOS Latest 12.1 / Any Android / ... (including version!!! e.g. Android 5.1 / i0S 10)

**...

**Comment by smsissuechecker** [comment]
Hi @pamela032709,

I'm the friendly issue checker.
It seems like (25.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
Hey,

the plugin uses .net standard. So it can't be the plugin's fault. Did you clean everything?
there was an issue some days ago that looked similar. #135 
It also contains a solution. Can you check?

**Comment by pamela032709** [comment]
Hi, I just look at #135. At this moment I am not able to change to netstandard.  Question is . with my current settings Framework  .Net Portable 4.5-Profile 111 can I still use this plugin?

**Comment by smstuebe** [comment]
see: https://docs.microsoft.com/en-us/dotnet/standard/net-standard#pcl-compatibility

PCL 111 is equivalent to netstandard 1.1
The plugin is netstandard 1.0 

So it is compatible (=the reason why it worked before). Means: I didn't change anything. So something is wrong with your build setup :(

**Comment by natevarghese** [comment]
I have this issue too since the latest Visual Studio update. 

 Error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?)


I am able to mitigate it sometimes as stated:
https://forums.xamarin.com/discussion/comment/380286#Comment_380286

However, I dont think updating mono is the answer because it throws my android project out of wack.

**Comment by pamela032709** [comment]
Thanks Nathan to report this as well. seriusly, it was driving crazy . cause as I mentioned before I been using it for a very long time. with no issues until now.

**Comment by natevarghese** [comment]
@pamela032709 any progress?

**Comment by pamela032709** [comment]
No , after I tried multiple things nothing seem to work. I decided to recreate my whole project using the latest netstandard. 
It was just a radical solution. 
Since , I didnt find a way out of that error.

**Comment by natevarghese** [comment]
I tried to go down that path but there were several blockers outside this plugin that prevented me from converting at the moment. ugh.

**Comment by pamela032709** [comment]
hasnt been easy . Im still working on the android part . two weeks or more working on the same thing

**Comment by natevarghese** [comment]
Maybe we can add this to the Plugin.Fingerprint.csproj file?

<PackageTargetFallback>
$(PackageTargetFallback);portable-win+net45+wp8+win81+wpa8
</PackageTargetFallback>

https://solidbrain.com/2017/09/12/xamarin-is-it-time-to-move-from-pcl-to-net-standard/

Thoughts?

**Comment by smstuebe** [comment]
@natevarghese ofc not. .net standard is the way to go. Sorry the eco system moves faster than 10 years ago

**Comment by natevarghese** [comment]
What are the consequences of adding it?

**Comment by MuneebSaeed** [comment]
Facing same issue since i updated Visual Studio for Mac Community
Version 8.2 (Build 1105).
I also changed .net standard but no progress.
I tried many solutions for build setup like changing .net standard, GUID's capitalisation and removing and adding reference multiple time. However there are other references which are not creating problems.  
Please do something it's really frustrating.

**Comment by wawoohdavid7** [comment]
any news on this?

**Comment by smstuebe** [comment]
New version will use AndroidX and netstandard 2.0.

**Comment by pamela032709** [comment]
news is - I dont think they will fix this . so you either move to netstandars wich is the worst thing to do or simply not use this plugin. Is been couple of weeks and this should be fixed by now it is not a hard fix.

**Comment by wawoohdavid7** [comment]
Does this mean that backward compatibility with PCL is not supported anymore?

**Comment by ronpf** [comment]
Pull the bandaid off an just convert to .NETStandard. It's the only way to stay compatible with this package and the rest of the Nuget ecosystem moving forward.
