### ISSUE TITLE
Adding more FingerprintAuthenticationResultStatus

### ISSUE THREAD

**Issue by arctouch-oberdanbitencourt** [smstuebe/xamarin-fingerprint#14]
I've come across the need of registering custom analytics events for result statuses that are unknown, like `TouchIDLockout`. I think some statuses can be exposed so the plugin provides the developer a custom way to handle results from the OS.

**Comment by smstuebe** [comment]
I have to investigate this. I try to avoid adding platform specific stuff to the API.

**Comment by nielscup** [comment]
I also would like the status exposed so I can handle them properly. Currently the only way to determine the status is via the ErrorMessage, but this is a localized string so not very useful.
