### ISSUE TITLE
.NETPortable,Version=v5.0, 4.5 conflicts

### ISSUE THREAD

**Issue by xmesaj2** [smstuebe/xamarin-fingerprint#140]
PCL build fails with NETPortable requiring ver 5.0, when targetting 4.5 due to Plugins.Fingerprint.Abstractions. This tends to happen in VS2019 only and not VS2017.
I know PCL is old, but it used to work all the time and still does in VS2017.

## Steps to reproduce

1. Create .Net Framework 4.5 PCL

2. Add Reference to Plugins.Fingerprint.Abstractions

3. Build

## Expected behavior
Build success

## Actual behavior
There are multiple different versions between projects in the same solution. Seems to be the problem here:

https://github.com/smstuebe/xamarin-fingerprint/blob/51474a490c6dd4899b459f0406ad3c9f92de8205/src/Plugin.Fingerprint.Abstractions/Plugin.Fingerprint.Abstractions.csproj#L18

https://github.com/smstuebe/xamarin-fingerprint/blob/51474a490c6dd4899b459f0406ad3c9f92de8205/src/MvvmCross.Plugins.Fingerprint/MvvmCross.Plugins.Fingerprint.csproj#L17

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** 1.4.9.0 (NuGet)

**Platform:** Android 9.0 / Visual Studio 2019

**Device:**  Nokia 8 TA-1012

**Comment by smsissuechecker** [comment]
Hi @xmesaj2,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.
