### ISSUE TITLE
This is not Samsung device returned from  CrossFingerprint.Current.IsAvailableAsync(true);

### ISSUE THREAD

**Issue by rickerk6gdo** [smstuebe/xamarin-fingerprint#142]
On the Andriod platform I get This is not Samsung device  when calling the function

 CrossFingerprint.Current.IsAvailableAsync(true);

I'm in debug mode.  

Visual Studio 2019 and I dont have a ProGuard.cfg file nor does the app have the proguard_xamarin.cfg

**Comment by smsissuechecker** [comment]
Hi @rickerk6gdo,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by developer9969** [comment]
@rickerk6gdo  hi there I am getting the same how did you resolve it?

**Comment by smstuebe** [comment]
@rickerk6gdo @developer9969 I have an issue template for a reason. please use it.
