### ISSUE TITLE
Fingerprint does not exist in the namespace 'Plugin' errors when I upgrade Visual Studio for Xcode 11 Previews to support iOS 13

### ISSUE THREAD

**Issue by umeshdhuri1048** [smstuebe/xamarin-fingerprint#145]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1.

2.

3.

## Expected behavior
Tell us what should happen

## Actual behavior
Tell us what happens instead

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)

**Device:** e.g. HTC Sensation /i Phone 7 ...

**Comment by smsissuechecker** [comment]
Hi @umeshdhuri1048,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by umeshdhuri1048** [comment]
I am getting below errors when I upgrade Visual Studio for Xcode 11 Previews to support iOS 13.

Error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?)
Error CS0246: The type or namespace name 'AuthenticationRequestConfiguration' could not be found (are you missing a using directive or an assembly reference?) (CS0246)
Below are the visual studio details Visual Studio for Mac version 8.3 Mono Freamwork MDK : Mono 6.4.0 Xamarin.Android Version : 10.0.0.43 Xamarin.iOS Version : 13.2.0.42 Mac OS X : 10.14.6

Thanks in advance.
