### ISSUE TITLE
iOS: Popup not show, only gray background

### ISSUE THREAD

**Issue by JavierMoraCasas** [smstuebe/xamarin-fingerprint#148]
When I make the invocation request for the fingerprint, the system message to appear is not showing a gray screen with transparency and without showing anything, but if I put my finger on the fingerprint reader if the screen appears. I have tested the invocation both normally and using "Device.BeginInvokeOnMainThread (async () => {};" in case it was something that does not run in the main thread but I get the same result.

Can anyone tell me what may be happening?

I've tried it on an iPhone 7 with S.O: 13.1.2

## Steps to reproduce

1. Set invocation var result = await CrossFingerprint.Current.AuthenticateAsync("Text");

2. Launch app

3. Click on button to launch fingerprint login

## Expected behavior
Information Popup

## Actual behavior
a gray screen with transparency and without showing anything, but if I put my finger on the fingerprint reader if the screen appears.

### Crashlog

nothing

## Configuration

**Version of the Plugin:** 1.4.9

**Platform:** iOS 13.1.2 

**Device:** iPhone 7

Please help, thanks!

**Comment by smsissuechecker** [comment]
Hi @JavierMoraCasas,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by pzimmermaninmo** [comment]
Javier, I believe this is a bug in iOS 13.1+ as I've seen the same using xamarin without this plugin.  Apparently if you also shake the device the alert will popup.  https://9to5mac.com/2019/09/30/ios-13-iphone-touch-id-login-bug/

**Comment by JanettHolst290490** [comment]
That's a super useful link. Thanks, this is really good to know!

**Comment by smstuebe** [comment]
Hey @pzimmermaninmo thanks for providing the link :)

**Comment by MalmoIt** [comment]
iOS 13.3 resolves this issue for us at least.
