### ISSUE TITLE
Position the window at the bottom

### ISSUE THREAD

**Issue by mdmota** [smstuebe/xamarin-fingerprint#149]
Is it possible to position the window at the bottom of the screen(Android and iOS)?

**Comment by smsissuechecker** [comment]
Hi @mdmota,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
Only on android if you use a custom dialog fragment. In the current version is an example.
But: You can save the effort. In the new version the plugin will use the standard BiometricPrompt that won't give you control over it's position (similar to iOS). But it will be shown at the bottom (at least on not custom ROMs.
