### ISSUE TITLE
The plugin does not work on VS 2019 (Windows) with a PCL xamarin project 

### ISSUE THREAD

**Issue by alfio-f96** [smstuebe/xamarin-fingerprint#153]
## Steps to reproduce

1. Install plugin;
2. Call a function of the plugin;
3. Build;

## Expected behavior
Start my app.

## Actual behavior
Error in log.

### Crashlog row 1
Gravity: Error
Code: Null
Description: The "FilterAssemblies" task failed unexpectedly".
System.IO.FileNotFoundException: File 'C:\Users\user\source\repos\ProjectName\ProjectName\bin\Debug\ProjectName.dll' do not found.
File Name: 'C:\Users\user\source\repos\ProjectName\ProjectName\bin\Debug\ProjectName.dll' in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) in Xamarin.Android.Tasks.FilterAssemblies.Execute() in Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   in Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ProjectName.Droid			

### Crashlog row 2
Gravity: Error
Code: CS0234   
Description: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin'...

## Configuration
Version of the Plugin: 1.4.9
Version of Visual Studio: 2019

**Comment by smsissuechecker** [comment]
Hi @alfio-f96,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
Nobody actually cares about supporting PCLs anymore. There is nothing I can do to help you. I'd suggest migrating to .netstandard like everybody else. It's not much effort, because you only get more APIs :)
