### ISSUE TITLE
[Question] When is the plugin targeted for release?

### ISSUE THREAD

**Issue by atantasook** [smstuebe/xamarin-fingerprint#156]
Hi, I see the plugin is still in alpha.  Is there a target release date? 

Thanks!

**Comment by marceloarchiza** [comment]
I was also wondering the same thing and I asked him on twitter: https://twitter.com/archiza/status/1206689891708325889

He needs to wait for Xamarin.AndroidX.Biometric to have a stable version, before making this a stable version.

**Comment by smstuebe** [comment]
What @marceloarchiza said. I just copy my answer and make it sticky.

> I can't release a stable version for now, because you can't release stable nuget packages that rely on pre-release packages. I've to wait until Xamarin.AndroidX.Biometric is released as stable package. They are preparing it and I'm watching closely. So stay tuned...
