### ISSUE TITLE
AndroidX ?

### ISSUE THREAD

**Issue by stephenhauck** [smstuebe/xamarin-fingerprint#157]
You mention in the documentation ...
_Install Android X Migration

Since version 2, this plugin uses Android X. You have to install Xamarin.AndroidX.Migration in your Android project._

That does not come up in the NuGet list .. what should I use ?

Thanks!

**Comment by smsissuechecker** [comment]
Hi @stephenhauck,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
@stephenhauck have you checked the "include prerelease" checkbox in your nuget search UI? You can't find it without, because AndroidX is not released as stable, yet.
https://www.nuget.org/packages/Xamarin.AndroidX.Migration/1.0.0-preview06

**Comment by smstuebe** [comment]
any comments?
