### ISSUE TITLE
Unable to activate instance of type Plugin.Fingerprint.Dialog.DialogFingerprintAuthenticationCallback from native handle 0xbfb8e10c (key_handle 0xa9cb158).

### ISSUE THREAD

**Issue by nielscup** [smstuebe/xamarin-fingerprint#16]
Tapping cancel in the fingerprint dialog in Android results in the following error: 

_Unable to activate instance of type Plugin.Fingerprint.Dialog.DialogFingerprintAuthenticationCallback from native handle 0xbfb8e10c (key_handle 0xa9cb158)._

I get this error in version 1.3.0-beta1, this worked fine in version 1.2.0

Additional info: 
InnerException message: _No constructor found for Plugin.Fingerprint.Dialog.DialogFingerprintAuthenticationCallback::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)_

**Comment by smstuebe** [comment]
should be fixed in 1.3.0-beta2
