### ISSUE TITLE
Getting "Failed to add reference" error about reference to System.Drawing.Common.dll when updating nuget package to 2.0 version 

### ISSUE THREAD

**Issue by atantasook** [smstuebe/xamarin-fingerprint#162]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. In Visual Studio, open your Xamarin solution.  
2. Right-click on the solution and 'Manage Nuget Packages for Solution.
3. Go to Updates tab.
4. Update Plugin.Fingerprint to version 2.0
5. Go through the prompts to update.

## Expected behavior
Nuget package is updated to version 2.0.0

## Actual behavior
Getting the error below:
Failed to add reference. The package 'Plugin.Fingerprint' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Reference unavailable.

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:**  v2.0.0.0
**Platform:** Xamarin Forms, 4.4, iOS 13.2, Android 10

**Comment by smsissuechecker** [comment]
Hi @atantasook,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
Hi @atantasook,

what are your target frameworks?
have you tried a clean install? Uninstall the old version and then install the new version manually?

**Comment by atantasook** [comment]
Hi, @smstuebe,

I'm targeting .Net Standard 2.0.  I tried clean install and got the same message.
I appreciate your help!

**Comment by smstuebe** [comment]
@atantasook Hmm I just created a new netstandard library and could install it without any problems.
Is you VS 2019 up to date? I've searched for your error and it looks like this was an issue late 2019.

**Comment by atantasook** [comment]
My VS is version 16.4.5 so it's currently the latest.  My netstandard library project was converted from PCL so maybe there is something to that.

**Comment by smstuebe** [comment]
ahh. can you create a clean one and try again? the conversion usually leaves in some unnecessary stuff.

**Comment by atantasook** [comment]
I was able to get through installation for the netstandard library project. Yay! Now, i get the same error on my iOS project.

**Comment by atantasook** [comment]
Changing my iOS project to PackageReference did the trick.
