### ISSUE TITLE
Need details

### ISSUE THREAD

**Issue by amr-moomen** [smstuebe/xamarin-fingerprint#163]
currently, my installed version is 1.4.9 and need to know what's the new features in version  2 to before I update.

**Comment by smsissuechecker** [comment]
Hi @amr-moomen,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
https://github.com/smstuebe/xamarin-fingerprint/blob/master/doc/changelog.md
