### ISSUE TITLE
Cannot install v2 on iOS, missing System.Drawing.Common.dll

### ISSUE THREAD

**Issue by cmdrew** [smstuebe/xamarin-fingerprint#164]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1.

2.

3.

## Expected behavior
Tell us what should happen

## Actual behavior
Tell us what happens instead

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)

**Device:** e.g. HTC Sensation /i Phone 7 ...

**Comment by smsissuechecker** [comment]
Hi @cmdrew,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by cmdrew** [comment]
Been using this plugin for a while but had an isue with v1.4.9 under Android failing to build so i updated my projects to use v2.  all went well in the shared and android project but when I tried to update the package on iOS I got an error saying 'Plugin.Fingerprint tried to add a framework reference to System.Drawing.Common.dll which is not in the GAC'.  trouble is i need v2 for android to build but can't upgrade iOS and as the calling format to AuthenticateAsync has changed now my iOS version won't build.

**Comment by smstuebe** [comment]
Please see: https://github.com/smstuebe/xamarin-fingerprint/issues/162

**Comment by cmdrew** [comment]
Yes I had seen this previously - the problem i am facing is that this is quite a bit project and even if I can get it to work in a test project it doesn't really help with this one.  I had thought about going down the packagemanager route but when-ever I make changes like that to a Xamarin Forms project it takes ages to get it to compile again.  At the moment I am building the Android version with 1.4.9 and then updating the nuget to v2 for iOS - not ideal but it works and gets me past some very tight deadlines...

**Comment by smstuebe** [comment]
@cmdrew have you tried to use PackageReference ind the Platform specific projects like suggested in the linked issue? This should be done quickly (open csproj and paste 3 lines).
