### ISSUE TITLE
Fingerprint.AuthenticateAsync fails on Android Face authentication if there are no stored fingerprint

### ISSUE THREAD

**Issue by atantasook** [smstuebe/xamarin-fingerprint#165]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Use an Android device that supports both Face and Fingerprint Authentication.  On the device, register your face and choose Face Recognition as the preferred biometric.  Make sure that there are no fingerprints registered.

2. Install v2.0 of Plugin-Fingerprint nuget package and all the dependencies into the appropriate projects in your Xamarin.Forms solution.

3. In the appropriate code where you will be implementing face authentication, make a call to Fingerprint.AuthenticateAsync(whateverAuthRequestConfig) and authenticate with the face that is stored.  Note that the result contains Authenticated=false.

## Expected behavior
The result should contain Authenticated=true.

## Actual behavior
The result contain Authenticated=false.

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

Plugin version: v2.0
Xamarin Forms version: v4.4
Platform: Android 9
Device: Samsung Galaxy S8 or any Android device that supports both Face and  Fingerprint authentication.

**Comment by smsissuechecker** [comment]
Hi @atantasook,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by atantasook** [comment]
Resubmittted issue with proper template so closing this one.
