### ISSUE TITLE
Failed to resolve type Plugin.Fingerprint.Abstractions.IFingerprint

### ISSUE THREAD

**Issue by yyuzyk** [smstuebe/xamarin-fingerprint#168]
Crash during start application on iOS.
Crash on MvvmCross 6. On MvvmCross 5 - works correct.

### Crashlog

MvvmCross.Exceptions.MvxException: Failed to construct and initialize ViewModel for type Core.ViewModels.LoginViewModel from locator MvxDefaultViewModelLocator - check InnerException for more information ---> MvvmCross.Exceptions.MvxException: Problem creating viewModel of type LoginViewModel ---> MvvmCross.Exceptions.MvxIoCResolveException: Failed to construct LoginViewModel ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> MvvmCross.Exceptions.MvxIoCResolveException: Failed to resolve type Plugin.Fingerprint.Abstractions.IFingerprint

## Configuration

**Version of the Plugin:** 2.0.0 - 2.1.1

**Platform:** iOS

**Device:** iPhone

MvvmCross 6.4.2

**Comment by smsissuechecker** [comment]
Hi @yyuzyk,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by S-Pourali** [comment]
I faced with this issue too in MvvmCross (v 7.1.2). as MvvmCross self mentioned ,resolving with type "Mvx.Resolve<T>()" is obsolete. current document is refered to old version of MvvmCross.

**Comment by S-Pourali** [comment]
Actually this is not an issue (my bad !! ), before resolving IFingerprint interface in IoC, just construct CrossFingerprint.Current using by LazyConstructAndRegisterSingleton when initialing app.
          
     Mvx.IoCProvider.LazyConstructAndRegisterSingleton(() => CrossFingerprint.Current);
then could resolve IFingerprint in any  ViewModel or even inject it.
     
    var isSuccess = Mvx.IoCProvider.TryResolve(out IFingerprint fpService);

thank you @smstuebe.

**Comment by filipoff2** [comment]
“Dirty deeds done dirt cheap!” by Bogusław Błoński https://link.medium.com/Yg7sYwWYeeb
