### ISSUE TITLE
readme.md - 404 at link to Current Activity Plugin 

### ISSUE THREAD

**Issue by ThomasCork** [smstuebe/xamarin-fingerprint#171]
## Steps to reproduce

1. Navigate to the repository page. Under Setup > Android. The link to the current activity plugin directs to a 404.

![image](https://user-images.githubusercontent.com/23264958/79132205-cb2aae00-7da1-11ea-9b86-68a8ad9bb37c.png)

## Expected behavior
You should be navigated to the repository, which is https://github.com/jamesmontemagno/CurrentActivityPlugin 

## Actual behavior
Navigation sends you to https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/CurrentActivity

![image](https://user-images.githubusercontent.com/23264958/79132234-dd0c5100-7da1-11ea-8aee-70f6ab221cf4.png)

**Comment by smsissuechecker** [comment]
Hi @ThomasCork,

I'm the friendly issue checker.
It seems like (62.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
