### ISSUE TITLE
On Android 9.0 and 8.0 authentication freezes itself when alternate authentication is allowed

### ISSUE THREAD

**Issue by Stavvor** [smstuebe/xamarin-fingerprint#175]
I noticed that second call to authentication with alternate authentication allowed is freezing the app for good Im not providing any code, but it's reproducable in your demo app

## Steps to reproduce

1. Build&Run Sample.Android project on Android 9.0 or 8.0

2. Select "Allow alternate authentication method" switch

3. Press "Authenticate" and perform authentication

4. Go back

5. Press "Authenticate" again

## Expected behavior

Authentication performs like usually

## Actual behavior

App freezes.  AuthenticateAsync does not return value, nor throws any exceptions.

*Note That* if you don't switch alternate authentication, everything works correct.
Also, it works ok on Android 10.0

### Crashlog

No crash

## Configuration

physical:

**Version of the Plugin:**  2.1.1 (latest)

**Platform:** Android 8.0 - API 26

**Device:** Nokia 8 TA-1004

emulated:

1)
**Version of the Plugin:** 2.1.1 (latest)

**Platform:** Android 8.0 - API 26

**Emulator:**  Pixel 2

2)
**Version of the Plugin:** 2.1.1 (latest)

**Platform:** Android 9.0 - API 28

**Emulator:**  Pixel 3xl

**Comment by smsissuechecker** [comment]
Hi @Stavvor,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by joseluisct** [comment]
I have the same issue in Android. My app/sample app freezes when alternate method is allowed. Tested on device with Android 9.
I have found how to solve this issue in the library solution:

- Update package Xamarin.AndroidX.Biometric to 1.0.1.1 in both projects Plugin.Fingerprint and Sample.Android.
- Add package Xamarin.AndroidX.AppCompat.Resources 1.0.1.1 Sample.Android (output log says it's required)

With the sample app it is working OK now. 
@smstuebe Could you update the package with this change? Thank you.

**Comment by joseluisct** [comment]
Adding the references to the packages Xamarin.AndroidX.Biometric to 1.0.1.1 and Xamarin.AndroidX.AppCompat.Resources 1.0.1.1 to my app and using current nuget version of the plugin it is working now.
This works: https://github.com/smstuebe/xamarin-fingerprint/issues/160#issuecomment-638084646

**Comment by Stavvor** [comment]
thanks @joseluisct :)
