### ISSUE TITLE
Custom text

### ISSUE THREAD

**Issue by stefancvetkovic** [smstuebe/xamarin-fingerprint#177]
Is there a way to put some custom message on popup section where is fingerprint icon?

**Comment by smsissuechecker** [comment]
Hi @stefancvetkovic,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
Like this? 
It's in the sample app.

https://github.com/smstuebe/xamarin-fingerprint/blob/master/src/Sample/MainPage.xaml.cs#L46-L51

reason is the marked label text.

![image](https://user-images.githubusercontent.com/7632775/81060395-a2926180-8ed2-11ea-8ba2-08f6c5c71a5e.png)

**Comment by stefancvetkovic** [comment]
Actually, I need to set empty title - mine applications crashes, telling me that Title needs to be presented (neither " " string with empty space is not working)
I need to have "Prove you have fingers to be centered" and to be able to manipulate with bottom text below image "Beruhre den Fingerabdrucksensor"
Thanks

**Comment by smstuebe** [comment]
No, that is not possible. The dialog is now a standard dialog. this is best practice. If a designer want's you to change it, tell him, that 
1. on iOS it's also not possible to modify it
2. google / android pushes hard to unify this authentication (old API is deprecated)
