### ISSUE TITLE
Plugin crashes when used on iPhone 4 (iOS 7)

### ISSUE THREAD

**Issue by nielscup** [smstuebe/xamarin-fingerprint#18]
LAContext is not available before iOS8, so the plugin (and the app using the plugin) crashes on an iPhone4 with the following error: _Wrapper type 'LocalAuthentication.LAContext' is missing its native ObjectiveC class 'LAContext'._

**Comment by smstuebe** [comment]
Thanks. I'll fix it.

**Comment by nielscup** [comment]
I already did! Check my pull request.

**Comment by smstuebe** [comment]
Thanks :+1: . ahh ok you updated the android PR. Mhh merge fun ^^ I'll have a look. Please send multiple PRs in the feature, if you find and fix more bugs.

**Comment by nielscup** [comment]
Yeah, that happened automatically, wasn't aware of that...
