### ISSUE TITLE
Can we able to add passcode login if invalid fingerprint given

### ISSUE THREAD

**Issue by irshadka** [smstuebe/xamarin-fingerprint#181]
Can we able to add passcode login if invalid fingerprint given.
If user given wrong fingerprint continuously can we use passcode for login.

**Comment by smsissuechecker** [comment]
Hi @irshadka,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
see: https://github.com/smstuebe/xamarin-fingerprint/blob/master/src/Plugin.Fingerprint/Abstractions/AuthenticationRequestConfiguration.cs#L42

Just set `AllowAlternativeAuthentication` to true.

**Comment by irshadka** [comment]
Okay Thanks
