### ISSUE TITLE
Plugin.Fingerprint.Dialog depecated?

### ISSUE THREAD

**Issue by DragonflyJones** [smstuebe/xamarin-fingerprint#183]
1. In VS for Mac, update packages in a Xamarin Forms project using Plugin.Fingerprint to the latest versions.

2. Clean and Rebuild. 

3. Note that Plugin.Fingerprint.Dialog is no longer available. (The type or namespace name Dialog does not exist in the namespace Plugin.Fingerprint...)

Without updating, the plugin works. This project was created about 18 months ago so I assume at that point Plugin.Fingerprint included Dialog. If this is no longer the case, what is the recommended direction?

**Comment by smsissuechecker** [comment]
Hi @DragonflyJones,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
Yes. There is now an official dialog (built-in in the Android API) called biometric prompt. Since 2.0 the plugin uses this one.

**Comment by DragonflyJones** [comment]
Got it, thanks!
