### ISSUE TITLE
FaceID option not showing on iOS 14 Beta 3

### ISSUE THREAD

**Issue by DaveDaBrave** [smstuebe/xamarin-fingerprint#187]
## Steps to reproduce

1. Open working (on iOS 13) App on iPhone XR with iOS 14 Beta 3 installed.

## Expected behavior
FaceID login should be triggered, if rights granted before and FaceID is set up on the device correctly and in the app to login.

## Actual behavior
No FaceID Login is triggered, the FaceID option is even not available anymore in our options. Looks like the device doesn't support it anymore.

## Configuration

**Version of the Plugin: 2.1.1**

**Platform: iOS 14 Beta 3**

**Device: iPhone XR**

**Comment by smsissuechecker** [comment]
Hi @DaveDaBrave,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
