### ISSUE TITLE
IsAvailableAsync() returns 'true' on Android 8.1

### ISSUE THREAD

**Issue by frarteaga** [smstuebe/xamarin-fingerprint#190]
## Steps to reproduce

1. Invoke `var result = await CrossFingerprint.Current.IsAvailableAsync()` on a device with Android 8.1 and no biometrics support.

## Expected behavior
Must return `false` in result var.

## Actual behavior
Get `true` in result var. See:

![imagen](https://user-images.githubusercontent.com/18072082/90687415-cd62b480-e23a-11ea-8547-382bb9bcab8c.png)

### Crashlog

No crash.

## Configuration

**Version of the Plugin:** 2.1.1

**Platform:** Android 8.1

**Device:** Samsung J7 (2016)

**Comment by smsissuechecker** [comment]
Hi @frarteaga,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by frarteaga** [comment]
I remove `true` value of optional parameter `allowAlternativeAuthentication` and then work as expected. Now I realize that there was no errors in the plugin.
