### ISSUE TITLE
AuthenticateAsync hang in request and never return on OnePlus 6T

### ISSUE THREAD

**Issue by preitzel** [smstuebe/xamarin-fingerprint#194]
I'm not getting the chance to retry fingerprint authentication if first try with a "none registered finger" on my OnePlus 6T.
When calling: await CrossFingerprint.Current.AuthenticateAsync(request) and system is not able to recognize my fingerprint the on-screen fingerprint reader just disappears without getting any result back. On my Samsung S8 it works fine

## Steps to reproduce

1.  Simply run the sample program coming with the downloaded code on a OnePlus 6T

2. Try identify yourself with a none registered finger

## Expected behavior
I would expect to get another chance to authenticate my self with a new touch

## Actual behavior
On the OnePlus 6T the finger touch reader just disappears and the CrossFingerprint.Current.AuthenticateAsync(request) never returns. Only way to cancel the request is swap to another program and back again

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin: 2.1.2

**Platform: Android 10, OxygenOS 10.3.5

**Device: OnePlus 6T

**Comment by smsissuechecker** [comment]
Hi @preitzel,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by matteopiccioni** [comment]
Hi, I have the same problem ... on my app released in the stores!
Unfortunately I don't have a OnePlus to test, 
could you try if with AllowAlternativeAuthentication = false you have the same problem?

**Comment by preitzel** [comment]
Hi,
Just tried it .. but still same problem. I'm sure I tried all kind of combinations of properies but with no success. My only way to solve this is to roll back to version 1.4.9 of Xamarin Fingerprint. I don't know if this will give you problem when you release to Google Play but it is worth trying until this get solved ..
