### ISSUE TITLE
[Bug] Android: Update Nuget to 2.1.3 AuthenticateAsync status always returned unknown error

### ISSUE THREAD

**Issue by sunkerGit** [smstuebe/xamarin-fingerprint#205]
auth = await CrossFingerprint.Current.AuthenticateAsync(dialogConfig, _cancel.Token); The Authenticate always returned an unknown error when touching the valid finger. this problem occurs when updating Nuget to 2.1.3. This is not happening on Nuget 2.1.2

## Steps to reproduce

1. Update Nuget 2.1.2 to 2.1.3
2. Close VS 2019
3. Delete Android: bin & obj folder
4. Open Project Solution
5. Set Startup project to Android
5. Rebuild All
6. Run the app

## Expected behavior
**With Xamarin.AndroidX.Biometric 1.1.0.1, the result would be:**
**Fingerprint Nuget 2.1.3:** Valid fingerprint should be returned status == success when process authentication

## Actual behavior
**With Xamarin.AndroidX.Biometric 1.1.0.1, the result would be:**
**Fingerprint Nuget 2.1.3:** Valid fingerprint returned status == Unkown error.
**Fingerprint Nuget 2.1.2:** Valid fingerprint returned status == Success.

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** 2.1.3

**AndroidX Nuget:** Xamarin.AndroidX.Biometric 1.1.0.1

**Platform:** Android 10

**Device:** Samsung S9

**Environment:** Mac OS Big Sur ver 11.2.3

**Comment by smsissuechecker** [comment]
Hi @sunkerGit,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
#206 was pushed in version 2.1.4 to nuget.

**Comment by sunkerGit** [comment]
Worked as expected! Well done
