### ISSUE TITLE
Feature request: Timeout waiting for the fingerprint result

### ISSUE THREAD

**Issue by mdima** [smstuebe/xamarin-fingerprint#208]
Hello, 
it would be useful to introduce a "timeout" property of the AuthenticationRequestConfiguration object in order to not to leave the application waiting indefinitely for a fingerprint scan. 

Thanks,
Michele

**Comment by smsissuechecker** [comment]
Hi @mdima,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by mdima** [comment]
Hello, sorry to all for not using the template, just this is a feature request, non an issue, and the template does not apply to it..

**Comment by smstuebe** [comment]
Have a look at the sample. You can do this with a cancellation token

**Comment by mdima** [comment]
Thank you @smstuebe , I will use that pattern. 

Michele
