### ISSUE TITLE
If Fingerprint recognition cancelled, plugin returns Failed rather than Canceled

### ISSUE THREAD

**Issue by gordonsaxby** [smstuebe/xamarin-fingerprint#212]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Run app to enable / open native Fingerprint recognition function

2. Touch anywhere off of the panel to close (cancel) it

## Expected behavior
Tell us what should happen
FingerprintAuthenticationResult.Status should be "Canceled"

## Actual behavior
Tell us what happens instead
FingerprintAuthenticationResult is set to "Failed"

Even though the ErrorMessage value is set to "Authentication cancelled"

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3
2.1.4

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)
Android version 10

**Device:** e.g. HTC Sensation /i Phone 7 ...
Nokia 3.4

**Comment by smsissuechecker** [comment]
Hi @gordonsaxby,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by Hooterr** [comment]
Yup can confirm that. It's very annoying.

**Comment by smstuebe** [comment]
@gordonsaxby 
should be fixed in v2.1.5.
