### ISSUE TITLE
App hangs under iOS 16 Beta at startup

### ISSUE THREAD

**Issue by DaveDaBrave** [smstuebe/xamarin-fingerprint#230]
Our app is hanging at startup and is not responsive like in production versions of iOS.
Under Android everything worked in Android 13 Beta-Releases and also now in production.

## Steps to reproduce

1. call CrossFingerprint.Current.AuthenticateAsync on an iOS 16 Beta device

2. app hangs and nothing is working

## Expected behavior
The user can authenticate within the app

## Actual behavior
The user cannot authenticate within the app

## Configuration

**Version of the Plugin:** 2.1.4

**Platform:** iOS 16 Beta (Build 20A5356a)

**Device:** iPhone XR

**Comment by smsissuechecker** [comment]
Hi @DaveDaBrave,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.
