### ISSUE TITLE
Failed resolution of: Landroidx/lifecycle/ViewModelProvider$KeyedFactory;

### ISSUE THREAD

**Issue by rogerskk** [smstuebe/xamarin-fingerprint#235]
## Steps to reproduce

1.Installed plugin according to this video: https://www.youtube.com/watch?v=k-eg3gcSMSU

2.Do the following: FingerprintAuthenticationResult result = await CrossFingerprint.Current.AuthenticateAsync (authRequest);

3. result.ErrorMessage = "Failed resolution of: Landroidx/lifecycle/ViewModelProvider$KeyedFactory;"

## Expected behavior
Should authenticate the user

## Actual behavior
Tell us what happens instead

### Crashlog
see error above

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3
Plugin version 2.1.5

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)
Android 13.0 - API 33

**Device:** e.g. HTC Sensation /i Phone 7 ...
Tested on both a Pixel 5 emulator and a Pixel 6 actual device.  Thinking it might have to do with the version of Xamarin.AndroidX.Lifecycle.Service I'm using maybe? I am on 2.4.1.2 of that.

**Comment by smsissuechecker** [comment]
Hi @rogerskk,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by rogerskk** [comment]
I was able to resolve this by updating Xamarin.AndroidX.Lifecycle.ViewModel and Xamarin.AndroidX.Lifecycle.ViewModelSavedState to the latest versions.  I also updated Xamarin.AndroidX.Lifecycle.Runtime and Xamarin.AndroidX.Lifecycle.LiveData to the latest version while I was at it.
