### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by smstuebe** [smstuebe/xamarin-fingerprint#35]

**Comment by smstuebe** [comment]
This is a test!

**Comment by smsissuechecker** [comment]
This is a test!

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the fiendly issue checker.
Thanks for using the issue template :kissing_heart:
I appreciate it very much. I'm sure, the maintainers of this

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the fiendly issue checker.
It seems like (7.657,01 %), you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.

Thanks!

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the fiendly issue checker.
It seems like (9.976,57 %), you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the fiendly issue checker.
It seems like (76,57 %), you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
