### ISSUE TITLE
sdfsdff

### ISSUE THREAD

**Issue by smstuebe** [smstuebe/xamarin-fingerprint#38]
d
## Expected behavior
Tell us what should happen

## Actual behavior
Tell us what happens instead

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the fiendly issue checker.
Thanks for using the issue template :kissing_heart:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the fiendly issue checker.
Thanks for using the issue template :kissing_heart:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the fiendly issue checker.
It seems like (62.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the fiendly issue checker.
It seems like (62.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the friendly issue checker.
It seems like (62.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
