### ISSUE TITLE
Xamarin fingerprint plugin issue

### ISSUE THREAD

**Issue by ksdavis1121** [smstuebe/xamarin-fingerprint#39]
**Version of the Plugin:** 1.3.0.0
Visual Studio 2013

The plugin Reference seems to be missing. When I compile I get this error: 

C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3274: The primary reference "Plugin.Fingerprint, Version=1.3.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile78".

Have you seen this error and is there a resolution?

**Comment by smsissuechecker** [comment]
Hi @smstuebe,

I'm the friendly issue checker.
It seems like (87.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
Uhh 2013 is pretty old and the plugin also uses .netstandard, wich is a new technology. I'm not sure, if VS 2013 supports it. Can you please try to update it. Or try to compile your project wir at least VS 2015? 

btw:  @smsissuechecker is right ^^
