### ISSUE TITLE
Dependency on .NETStandard.Library (>= 1.6.0)

### ISSUE THREAD

**Issue by rohitvipin** [smstuebe/xamarin-fingerprint#46]
None of the other plugins have this dependency. i don't want to add this dependency when i am using PCL or Shared project.

**Comment by smsissuechecker** [comment]
Hi @rohitvipin,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
There should be nothing additionally installed, if you install it in your PCL https://docs.microsoft.com/en-us/dotnet/articles/standard/library 

Xamrin.iOS and Xamarin.Android = .NETStandard.Library

What's your problem?

**Comment by smstuebe** [comment]
See:

![image](https://cloud.githubusercontent.com/assets/7632775/23563470/18ce7a96-0047-11e7-9fcd-edc1798bd09d.png)

**Comment by rohitvipin** [comment]
Okay, thank you. I had to move my PCL to 259 and it worked. Thanks for answering the question.

**Comment by smstuebe** [comment]
@rohitvipin Wich Profile did you have before?

**Comment by rohitvipin** [comment]
111 also, i had .net core project with in the solution.

**Comment by smstuebe** [comment]
Hmm the PCL from the screenshot is Profile 111 and it installed without problems. :(
