### ISSUE TITLE
SamsungFingerprintImplementation returns wrong error after failed attempts

### ISSUE THREAD

**Issue by nielscup** [smstuebe/xamarin-fingerprint#47]
## Steps to reproduce

1. Start the sample app on a Samsung device
2. Press AuthenticateLocalized
3. Authenticate with your wrong finger until the authenticationdialog disappears: you get the **TooManyAttempts** message: **this is correct**
4. Press AuthenticateLocalized again
5. Authenticate with your wrong finger again until the authenticationdialog disappears: now you  get the **failed** message: **this is not expected because I cannot provide the user with any useful information based on this message.**
6. Press AuthenticateLocalized again
7. the authenticationdialog disappears: now you  get the **UnknownError** message: **this is not expected because I cannot provide the user with any useful information based on this message.**

## Expected behavior
The same behaviour as a non Samsung device: always show the TooManyAttempts message while fingerprint is locked due to too many attempts.

## Actual behavior
see reproduction steps

### Crashlog

n/a

## Configuration

**Version of the Plugin:** 1.4.2

**Platform:** Android 6.0.1

**Device:** e.g. Tested on Samsung Galaxy S7

**Comment by smsissuechecker** [comment]
Hi @nielscup,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
2.0.0 has no samsung specific implementation anymore.
