### ISSUE TITLE
.NET Standard and Regular PCL support

### ISSUE THREAD

**Issue by renzska** [smstuebe/xamarin-fingerprint#49]
## Steps to reproduce

1. Add the plugin to a non .net-standard project (PCL).

2. Try to compile.

## Expected behavior

It should compile.

## Actual behavior

It errors with the following:

```
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/4.5/Microsoft.Common.targets(3,3): Warning MSB3274: The primary reference "Plugin.Fingerprint.Abstractions" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile78". (MSB3274) (Mobile.Core)
```

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** 1.4.2

**Platform:** Xamarin Studio 6.3

**Device:** Mac

**Comment by smsissuechecker** [comment]
Hi @renzska,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
see #44

**Comment by renzska** [comment]
Thanks. Added additional info to #44.
