### ISSUE TITLE
Default setup uses white fragment with white fingerprint icon

### ISSUE THREAD

**Issue by ChaseFlorell** [smstuebe/xamarin-fingerprint#51]
When I create a default setup using a light theme, the baked in fragment shows a white background with a white fingerprint icon. I'd like the ability to tint the icon to a different color if possible.

I know we can create a custom Fragment, but I'm not sure how that works within your plugin. I'd like to keep everything else exactly as it is (white background, black text), but simply color the icon something different so that it is visible.

## Steps to reproduce

1. Follow initial setup and use the following theme in your android app ``Theme.AppCompat.Light.NoActionBar

2. Test

## Expected behavior
Fingerprint image should be visible on the dialog fragment

## Actual behavior
Fingerprint image is the same color as the background (white).

## Configuration

**Version of the Plugin:** 1.4.2

**Platform:** Android 7.1

**Device:** Google Pixel XL

**Comment by smsissuechecker** [comment]
Hi @ChaseFlorell,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by ChaseFlorell** [comment]
Well I took a stab at tinting your image and it seems to work. For anyone else...

```csharp
public class CustomFingerprintDialogFragment : FingerprintDialogFragment
{
    public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
    {
        var view=base.OnCreateView(inflater, container, savedInstanceState);

        var image = view.FindViewById<ImageView>(Resource.Id.fingerprint_imgFingerprint);
        image.SetColorFilter(Color.ParseColor("#000000")); // black 
            
        return view;
    }
}
```

**Comment by smstuebe** [comment]
> I know we can create a custom Fragment, but I'm not sure how that works within your plugin.

See the documentation: https://github.com/smstuebe/xamarin-fingerprint#configuration

    public class MyCustomDialogFragment : FingerprintDialogFragment
    {
        public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
        {
            var view = base.OnCreateView(inflater, container, savedInstanceState);
            var image = view.FindViewById<ImageView>(Resource.Id.fingerprint_imgFingerprint);
            image.SetImageResource(Resource.Drawable.fingerprint_black);
            return view;
        }
    }

Unfortunately, the fragment is calling `ClearColorFilter()` after each animation. That's why you have to add a black copy of the icon to your project.

I'll change the code, so you will be able to set a tint for the icon in the next release.

**Comment by ChaseFlorell** [comment]
That would be pretty cool @smstuebe. For now my workaround will do just fine.

**Comment by smstuebe** [comment]
Sure? have you tested a negative try where the icon turns red and then back to white. I'd be suprised, that it turns back to black.

**Comment by ChaseFlorell** [comment]
ah, you are right. If I scan the correct finger, it goes green then disappears (that what I tested). When I use the incorrect finger, it goes red then goes white.

**Comment by ChaseFlorell** [comment]
Not sure I can submit a PR, but here's my thought.

```csharp
        private async Task AnimateFailedTryAsync()
        {
            if (_icon == null)
                return;
            var originalColorFilter = _icon.ColorFilter;
            _icon.SetColorFilter(NegativeColor);
            var shake = ObjectAnimator.OfFloat(_icon, "translationX", -10f, 10f);
            shake.SetDuration(500);
            shake.SetInterpolator(new CycleInterpolator(5));
            await shake.StartAsync();
            _icon.SetColorFilter(originalColorFilter);
        }
```

**Comment by smstuebe** [comment]
I'll make it completely customizable like NegativeColor. I may add a styling mechanism, so you don't have to create a custom just class for styling.

**Comment by NightOwlCoder** [comment]
Hey guys, was this fixed?
I'm having a hard time on my app with the white on white...

**Comment by smstuebe** [comment]
oupsi, no. I'll move it to Milestone 1.4.6.

**Comment by ruisilva450** [comment]
As of now there is a way that I can apply my own FingerprintCustomDialog.axml?
If I do that in the OnCreateView it will loose the bindings even if I use the same resource ids that you use in your .axml file.

**Comment by foehammer88** [comment]
@smstuebe any update on this?

**Comment by smstuebe** [comment]
-> 1.4.6
You can set `DefaultColor` in a custom dialog now.

**Comment by marualderete** [comment]
@smstuebe is there any way to customize the text color of  "Cancel" button? It is taking native color right now.

Kind regards

**Comment by dushani88** [comment]
@smstuebe, is there any example on how to set "DefaultColor"? I'm finding it difficult to set it.

Thanks

**Comment by alvynfash** [comment]
> @smstuebe any update on this?

You can do this => 
`public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
        {
            return inflater.Inflate(Resource.Layout.some_xml_file, container, false);
        }`

**Comment by BogaDev** [comment]
> -> 1.4.6
> You can set `DefaultColor` in a custom dialog now.

Hello! How can I change tooltip text color in the dialog?

**Comment by alvynfash** [comment]
> > -> 1.4.6
> > You can set `DefaultColor` in a custom dialog now.
> 
> Hello! How can I change tooltip text color in the dialog?

@BogaDev get reference to the widget in the onCreateView override then customise it as you want

**Comment by BogaDev** [comment]
> > > -> 1.4.6
> > > You can set `DefaultColor` in a custom dialog now.
> > 
> > 
> > Hello! How can I change tooltip text color in the dialog?
> 
> @BogaDev get reference to the widget in the onCreateView override then customise it as you want

Thank you for the answer! Could you please give an example? Because Im really stuck at this point

**Comment by georgeharnwell** [comment]
I could do with some examples on this. I can only seem to find the background property to update. Not text color.

**Comment by BogaDev** [comment]
> 
> 
> I could do with some examples on this. I can only seem to find the background property to update. Not text color.

I found how to change background color, that was pretty simple, but text color changing looks really complicated. If you could help, I would be very grateful

**Comment by alvynfash** [comment]
@BogaDev @georgeharnwell @foehammer88 @ruisilva450 @marualderete 
So i finally got the time to upload my implementation that allows me use my custom xml layout, reference widgets from the layout in my extended FingerprintDialogFragment => "ZetagikCustomFingerprintDialogFragment" and even change the dialog type to "BottomSheetDialog".
Also, don't forget to modify your MainApplication.cs to use this customised FingerprintDialogFragment.

[https://github.com/smstuebe/xamarin-fingerprint/compare/master...alvynfash:master#diff-09cd23b15e5953047dcbaef854650e48](url)

**Comment by georgeharnwell** [comment]
That is NICE! Thank you!

**Comment by BogaDev** [comment]
@alvynfash you are just... wizard.
Thank you so much
