### ISSUE TITLE
Built against the .NETPortable,Version=v5.0 ?

### ISSUE THREAD

**Issue by ronpf** [smstuebe/xamarin-fingerprint#58]
I'm testing Visual Studio for Mac and when building a Xamarin.Forms app I'm seeing these errors.
The same project builds without issue using Xamarin Studio on the same machine.

This may not be a problem with your plugin but for whatever reason I can't use VS

MSBUILD :  
/Library/Frameworks/Mono.framework/Versions/4.8.1/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1980,5): warning MSB3274: The primary reference "Plugin.Fingerprint.Abstractions" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111".
/Library/Frameworks/Mono.framework/Versions/4.8.1/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1980,5): warning MSB3275: The primary reference "Plugin.Fingerprint" could not be resolved because it has an indirect dependency on the assembly "Plugin.Fingerprint.Abstractions, Version=1.4.3.0, Culture=neutral, PublicKeyToken=null" which was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111".
/Library/Frameworks/Mono.framework/Versions/4.8.1/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1980,5): warning MSB3274: The primary reference "Plugin.Fingerprint" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111".

## Steps to reproduce

1. Build app using Xamarin Studio on Mac - No issues

2. Build app using Visual Studio for Mac - Build Errors

3.

## Expected behavior
No build errors

## Actual behavior
See errors

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3
1.4.3

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)
PCL, Xamarin.Forms, iOS, Android

**Device:** e.g. HTC Sensation /i Phone 7 ...

**Comment by smsissuechecker** [comment]
Hi @ronpf,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
Hmm VS for Mac is a Preview. If I have time, 
Looks like a bug: https://forums.xamarin.com/discussion/92037/namespace-not-found-in-vs-mac-works-fine-in-xs-mac

**Comment by NightOwlCoder** [comment]
@smstuebe 
Hey guys!
I've been trying to move to VS for Mac, now that we have the official release but I'm still getting the same error.

I've found this issue on another package:
https://github.com/dotnet/roslyn/issues/11067

where looks like the package author could do something to make it better?
https://nicksnettravels.builttoroam.com/post/2016/12/06/When-I-grow-up-I-want-to-be-a-NETStandard-Library!.aspx

This is the last package on our projects that are holding us from moving forward...
Any ideas would be welcome,
.NightOwl
