### ISSUE TITLE
Enter code Error: Fallback authentication mechanism selected.

### ISSUE THREAD

**Issue by alvarocasado** [smstuebe/xamarin-fingerprint#60]
On IOs, trying to enter the authentication password after failing the fingerprint authentication, returns the following error: 
Plugin.Fingerprint.Abstractions.FingerprintAuthenticationResultStatus.FallbackRequested : Fallback authentication mechanism selected.

This can be seen in the SMS.Fingerprint.Sample.iOS project.

## Steps to reproduce

1. Launch SMS.Fingerprint.Sample.iOS proyect

2. Try to authenticate with wrong fingerprint. Enter code message appears.

3. Click on "Enter code".

## Expected behavior
Numeric keyboard to enter the code.

## Actual behavior
Not loged. The option to enter the code does not appear 

## Configuration

**Version of the Plugin:** 1.4.3
**Platform:** iOS 10.2
**Device:** i Phone 5s

This issue is solved changing the following line (31) of the project Plugin.Fingerprint.iOS, class FingerprintImplementation, method NativeAuthenticateAsync:

resTuple = await _context.EvaluatePolicyAsync(LAPolicy.DeviceOwnerAuthenticationWithBiometrics, authRequestConfig.Reason);

by

resTuple = await _context.EvaluatePolicyAsync(LAPolicy.DeviceOwnerAuthentication, authRequestConfig.Reason);

**Comment by smsissuechecker** [comment]
Hi @alvarocasado,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
Simply changing it, can cause unwanted behavior on existing apps. I might make it configurable.

**Comment by alvarocasado** [comment]
Yep, making it configurable is better than hardcode it.
Cheers.

**Comment by AndriyMahera** [comment]
Hi @smstuebe ,
Do you work on resolving this issue?
I'd want to know because this is important for my application. Should I wait for solution soon  or make some workaround by myself?
Have a nice day.

**Comment by smstuebe** [comment]
If Quake Champions allows me to do something different, I'll have a look at it at the weekend.

**Comment by AndriyMahera** [comment]
Ok, thanks

**Comment by smstuebe** [comment]
Included in 1.4.4.
Feedback?

**Comment by AndriyMahera** [comment]
@smstuebe ,everything works good, very grateful.

**Comment by yehudagot** [comment]
If you're trying to disable the passcode fallback option in the biometric prompt on iOS, you can do so by setting context.LocalizedFallbackTitle to an empty string (""). This will prevent the system from showing the "Enter Passcode" option if the biometric authentication fails, making it strictly a biometric-only prompt.

Here’s an example in C# for Xamarin.iOS:
```
var context = new LAContext();
context.LocalizedReason = "Authenticate to unlock";
context.LocalizedFallbackTitle = ""; // This disables the fallback option

var authResult = await context.EvaluatePolicyAsync(LAPolicy.DeviceOwnerAuthenticationWithBiometrics, context.LocalizedReason);

if (authResult.Item1) // Authentication succeeded
{
    // Continue with your secured action
}
else
{
    Console.WriteLine("Authentication failed: " + authResult.Item2?.LocalizedDescription);
    // Handle the failed authentication
}
```
