### ISSUE TITLE
Fingerprint reference issue (target version)

### ISSUE THREAD

**Issue by hemakumarveerla** [smstuebe/xamarin-fingerprint#63]
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: **# The primary reference "Plugin.Fingerprint.Abstractions" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259**".
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3275: The primary reference "Plugin.Fingerprint" could not be resolved because it has an indirect dependency on the assembly "Plugin.Fingerprint.Abstractions, Version=1.4.2.0, Culture=neutral, PublicKeyToken=null" which was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Plugin.Fingerprint" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".
1>D:\Users\hemakumarv\Desktop\MobileID\MobileID\CommonUI\UserLoginWithAuthenticationPage.xaml.cs(7,14,7,25): error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?)
1>D:\Users\hemakumarv\Desktop\MobileID\MobileID\CommonUI\HomePage.xaml.cs(3,14,3,25): error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?)
1>D:\Users\hemakumarv\Desktop\MobileID\MobileID\CommonUI\TouchIDSettingPage.xaml.cs(18,14,18,25): error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?)
1>D:\Users\hemakumarv\Desktop\MobileID\MobileID\CommonUI\SetupUserRegistrationPage.xaml.cs(8,14,8,25): error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?)

## Steps to reproduce
1. updated the nugget package of plugin.fingerprint to V1.4.3 and build the solution  in VS 2015 with update 3 then getting the errors saying 

2.**The primary reference "Plugin.Fingerprint" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".
1>D:\Users\hemakumarv\Desktop\MobileID\MobileID\CommonUI\UserLoginWithAuthenticationPage.xaml.cs(7,14,7,25): error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?)**

3.

## Expected behavior
build error should not come.

## Actual behavior
Tell us what happens instead

build error is coming

## Configuration

**Version of the Plugin:** e.g. 1.4.3

**Platform:** e.g. Android API 23 version 4.5

**Device:** e.g

**Comment by smsissuechecker** [comment]
Hi @hemakumarveerla,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
This happens, if your system is not up to date. Please install every update for VS 2015 so that it can handle .NETStandard libraries.
