### ISSUE TITLE
AuthenticateAsync returns UnknownError instantly for consequent calls after initial TooManyAttempts

### ISSUE THREAD

**Issue by ZoranBebic** [smstuebe/xamarin-fingerprint#65]
Android: AuthenticateAsync fails after non deterministic amount of failed attempts (~3-5). Sometimes if will stop scanning (and return false result) after 3 and sometimes after 5 attempts. But that's minor issue however it should be possible to setup how many attempts user has before dialog closes or not?

What is breaking issue is the following scenario. Assume we have used invalid finger to generate 3-5 failed attempts. After that the method automatically fails (Status = UnknownError) for variable set of time (1-2 minutes) and for equal amount of failed attempts. Waiting it out will reset and continue to work as expected until this same scenario happens again. tested on Samsung Galaxy S6 w/ Android 7.0

## Steps to reproduce

1. call var result = await CrossFingerprint.Current.AuthenticateAsync("Swipe finger");

2. create failed attempts (3-5) using short presses or otherwise

3. call 1.) again

## Expected behavior
a dialog should appear waiting for finger scan

## Actual behavior
the call under 3.) fails automatically with Status = UnknownError. Waiting to perform a call under 3.) for few minutes will work as expected

## Configuration

**Version of the Plugin:** 1.4.4

**Platform:** Android 7.0

**Device:** Samsung Galaxy S6

**Comment by smsissuechecker** [comment]
Hi @ZoranBebic,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
Is there something interessting on the device log while executing the 3 steps?

**Comment by ZoranBebic** [comment]
There is nothing special at all going on in device log and as I experimented a bit more this happens to be the expected behavior. What happens is that after TooManyAttempts happens hardware/driver/whatever goes into some sort of cool-down period during which even if you initiate new scan will get not Failed status but UnknownError iirc. 

Can you play out this scenario and see what is the original error you get from the system before you return your status?

**Comment by NightOwlCoder** [comment]
Hey friends, just got the exactly same repro steps on a Pixel XL.
Even the wait time.

Any work arounds?

**Comment by smstuebe** [comment]
I can't spot any function to detect if the cooldown is active. I'm not sure if want to implement a workaround in the plugin itself, because this is highly vendor specific. (e.g. https://stackoverflow.com/questions/33472447/fingerprint-too-many-attempts-issue)

You can do it on your own. Disable your authentication for 31s if the plugin returns TooManyAttempts.
