### ISSUE TITLE
IsAvailableAsync() returns 'true' for iPhone 5C (iOS 10.3.2)

### ISSUE THREAD

**Issue by ehuna** [smstuebe/xamarin-fingerprint#72]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Use an iPhone 5C

2. Call 'result = await _fingerprint.IsAvailableAsync(false);'

## Expected behavior
Get back 'false' in result; the iPhone 5C does not have a fingerprint sensor.

## Actual behavior
Got back 'true' in result.

### Crashlog

No crashes.

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3
1.4.5
**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)
iOS 10.3.2
**Device:** e.g. HTC Sensation /i Phone 7 ...
iPhone 5C

**Comment by smsissuechecker** [comment]
Hi @ehuna,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.
