### ISSUE TITLE
Remove iOS default dialog

### ISSUE THREAD

**Issue by trqvinh90** [smstuebe/xamarin-fingerprint#76]
In Android, this option work fine with no dialog showing up.
Is this work the same in iOS or am I miss something?

**Comment by smsissuechecker** [comment]
Hi @trqvinh90,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
Please read the documentation:

https://github.com/smstuebe/xamarin-fingerprint/blob/master/src/Plugin.Fingerprint.Abstractions/AuthenticationRequestConfiguration.cs#L25

and

https://github.com/smstuebe/xamarin-fingerprint/blob/master/README.md#limitations

I can state it more clear if you want. The iOS API doesn't allow to hide the standard dialog.
