### ISSUE TITLE
Java.Lang.IllegalStateException: Fragment FingerprintDialogFragment not attached to Activity on samsung s5 device

### ISSUE THREAD

**Issue by ornolisvt** [smstuebe/xamarin-fingerprint#77]
I got this error on samsung galaxy s5 device, stack trace:
ava.Lang.IllegalStateException: Fragment FingerprintDialogFragment{c6ad194} not attached to Activity
09-15 17:45:38.168 I/MonoDroid(32669):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-15 17:45:38.168 I/MonoDroid(32669):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <6cd960837cc24c26bab2a0a29b597627>:0 
09-15 17:45:38.168 I/MonoDroid(32669):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <6cd960837cc24c26bab2a0a29b597627>:0 
09-15 17:45:38.168 I/MonoDroid(32669):   at Android.App.Fragment.get_Resources () [0x0000a] in <d278c06ad5684d6882c743a94a93ebc2>:0 
09-15 17:45:38.168 I/MonoDroid(32669):   at Plugin.Fingerprint.Dialog.FingerprintDialogFragment+<AnimateFailedTryAsync>d__36.MoveNext () [0x00045] in <4361465ae9654be1acd9cb583ba64c1a>:0 
09-15 17:45:38.168 I/MonoDroid(32669): --- End of stack trace from previous location where exception was thrown ---
09-15 17:45:38.168 I/MonoDroid(32669):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-15 17:45:38.168 I/MonoDroid(32669):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-15 17:45:38.168 I/MonoDroid(32669):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-15 17:45:38.168 I/MonoDroid(32669):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-15 17:45:38.168 I/MonoDroid(32669):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-15 17:45:38.168 I/MonoDroid(32669):   at Plugin.Fingerprint.Dialog.FingerprintDialogFragment+<OnFailedTry>d__33.MoveNext () [0x00069] in <4361465ae9654be1acd9cb583ba64c1a>:0 
09-15 17:45:38.168 I/MonoDroid(32669): --- End of stack trace from previous location where exception was thrown ---
09-15 17:45:38.168 I/MonoDroid(32669):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-15 17:45:38.168 I/MonoDroid(32669):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 

Please help with this error

**Comment by smsissuechecker** [comment]
Hi @ornolisvt,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
