### ISSUE TITLE
IsAvailableAsync() returns false also for iPad devices

### ISSUE THREAD

**Issue by grammatn** [smstuebe/xamarin-fingerprint#78]
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Implement in an empty project some code to test the plugin and call the IsAvailableAsync()

2. Select any iPad with TouchID. After starting the emulator go to Hardware -> Touch ID -> Activate the choice Enrolled

## Expected behavior
It should return true

## Actual behavior
It returns false

### Crashlog

No crashlog

## Configuration

**Version of the Plugin:1.4.5

**Platform: iOS 10.1 and recently tested also to 11

**Device: iPad Pro and iPad (5th generation)

**Comment by smstuebe** [comment]
I think this is a framework bug: https://stackoverflow.com/questions/46188245/ios-11-simulator-not-allowing-lacontext-and-faceid
