### ISSUE TITLE
Authentication based on callback without dialog

### ISSUE THREAD

**Issue by ruisilva450** [smstuebe/xamarin-fingerprint#81]
Hi, I want to be able to get the fingerprint authentication active without the dialog.

I have a case where I need to have a screen that provides authentication via PIN AND fingerprint. On this screen I need to be able to keep the fingerprint sensor ready in case the user uses it without the need for a dialog to appear (this causes the need for user to tap a button of some kind on the previous PIN screen, which I don't want to have).

## Steps to reproduce

1. Have a screen with PIN and fingerprint input

2. Start the sensor without the dialog

## Expected behavior
The dialog doesn't exists and the sensor is ready to give a callback when the user uses it.

## Actual behavior
The dialog appears.

### Crashlog
None

## Configuration

**Version of the Plugin: 1.4.5

**Platform:** e.g. iOS10+ / Android 6.0+ / UWP

**Device:** N/A

**Comment by smsissuechecker** [comment]
Hi @ruisilva450,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
Have you seen? 

https://github.com/smstuebe/xamarin-fingerprint/blob/0a2f2699c44cde97cd43080a0264477e404df347/src/Plugin.Fingerprint.Abstractions/AuthenticationRequestConfiguration.cs#L23-L28

**Comment by ruisilva450** [comment]
Thank you. 
I didn't saw that and maybe it's because I was testing on UWP expecting the same behavior...

**Comment by smstuebe** [comment]
Unfortunately, this feature can be only used on Android :/
