### ISSUE TITLE
Android Fallback always present

### ISSUE THREAD

**Issue by ruisilva450** [smstuebe/xamarin-fingerprint#82]
I'm trying to hide the fallback option but on Android it just keeps showing.

## Steps to reproduce

1. Use this code:
```
var config = new AuthenticationRequestConfiguration("Prove you have fingers!")
                {
                    AllowAlternativeAuthentication = false,
                    FallbackTitle = string.Empty
                };
var result = await CrossFingerprint.Current.AuthenticateAsync(config);
```
## Expected behavior
![image](https://user-images.githubusercontent.com/5648218/32545577-0e4cc2ca-c474-11e7-816e-7fa9a385e7a6.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/5648218/32545622-3227c5a0-c474-11e7-897a-9dbfc0af42a8.png)

### Crashlog

Doesn't apply (I think)

## Configuration

**Version of the Plugin:** 1.4.5

**Platform:** e.g. Android 7.0

**Device:** e.g. Xiaomi Redmi Note 4

**Comment by smsissuechecker** [comment]
Hi @ruisilva450,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by ruisilva450** [comment]
I've tried to track the issue and it appears that the option "AllowAlternativeAuthentication" in config isn't being used at all when trying to show the dialog.
https://github.com/smstuebe/xamarin-fingerprint/blob/master/src/Plugin.Fingerprint.Android/Dialog/FingerprintDialogFragment.cs#L93

Btw, why the dialog is not the native one in the expected behavior? There is a way to customize this far?

**Comment by JDubDev** [comment]
I can confirm I'm seeing the same behavior.

**Comment by tenneyb** [comment]
Has anyone gotten a Title like above "Sign In" to show up? if so how :)

**Comment by galadril** [comment]
Please add a possibility to remove the fallback button
