### ISSUE TITLE
Android without Forms

### ISSUE THREAD

**Issue by mister-giga** [smstuebe/xamarin-fingerprint#88]
I have used this plugin successfully with Xamarin.Forms, but now when I install this into my  another Xamarin.Android project (without forms), calling
   await Plugin.Fingerprint.CrossFingerprint.Current.AuthenticateAsync("reason");
throws System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

**Comment by smsissuechecker** [comment]
Hi @mister-giga,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
Please provide more information... like code, stacktrace, etc.
