### ISSUE TITLE
Check the types of biometric authentication supported

### ISSUE THREAD

**Issue by luisresende247** [smstuebe/xamarin-fingerprint#91]
In iOS 11 it's possible to check LABiometryType to know if the device supports Face ID or Touch ID.

Do you think this is something you can implement or should I raise a PR?

Cheers

**Comment by smsissuechecker** [comment]
Hi @luisresende247,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment]
Hmm no you can't check it upfront. You will only get the value **after** a successful authentication.
https://developer.apple.com/documentation/localauthentication/lacontext/2867583-biometrytype

> This property is only set when canEvaluatePolicy(_:error:) succeeds for a biometric policy. The default value is LABiometryNone.

**Comment by luisresende247** [comment]
I know but you could change _GetAvailabilityAsync_ to _GetAvailabilityAsync(bool allowAlternativeAuthentication = false, bool getAvailabilityType = false)_ and after canEvaluatePolicy(_:error:) return the type.

So in **FingerprintAvailability** you could add AvailableTouchID and AvailableFaceID.

Does it make sense?

**Comment by smstuebe** [comment]
-> 1.4.6
