### ISSUE TITLE
Estimated general release

### ISSUE THREAD

**Issue by Springham** [smstuebe/xamarin-fingerprint#93]
The latest version of this plugin has been in beta since July 2017.
Is there any estimate of when 1.4.6 will be out of the beta channel?

**Comment by smsissuechecker** [comment]
Hi @Springham,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!
