### ISSUE TITLE
Use Android P fingerprint dialog

### ISSUE THREAD

**Issue by smstuebe** [smstuebe/xamarin-fingerprint#97]
Android P will bring us a new fingerprint dialog and we will be forced to use it (hopefully a support package will be provided).

- [ ] investigate API https://developer.android.com/reference/android/hardware/fingerprint/FingerprintDialog.html
https://medium.com/exploring-android/exploring-android-p-fingerprint-dialog-fa672ae62c6f
- [ ] implement it
- [ ] decide how we handle Samsung stuff

**Comment by MdNaushad** [comment]
Is this completed?

**Comment by smstuebe** [comment]
no

**Comment by smstuebe** [comment]
disucssion goes on here: #151
