### ISSUE TITLE
MvvmCross 6.0

### ISSUE THREAD

**Issue by smstuebe** [smstuebe/xamarin-fingerprint#98]
convert mvx plugin to mvx 6.0

**Comment by luisresende247** [comment]
Hi

Do you have an ETA on this? Also how do I make 1.4.7 work with Mvx 6?

Thanks

**Comment by smstuebe** [comment]
ETA?

> Also how do I make 1.4.7 work with Mvx 6?

Just use the non mvx version and do `Mvx.LazyConstructAndRegisterSingleton<ISettings>(() => CrossFingerprint.Current);` in your Setup.cs files

**Comment by luisresende247** [comment]
Estimated time of arrival. A release date in mind.

Thanks that worked 👍

**Comment by JoshuaLogue** [comment]
Any update on this? Using MvvmCross 6.2.0 with 1.4.7 of the fingerprint plugin.

When I do CrossFingerprint.Current I get the error that it does not exist in the current context.
I have included the using statements for Plugin.Fingerprint and Plugin.Fingerprint.Abstraction
